version: '3.7'
services:
  portainer:
    image: portainer/portainer
    ports:
      - '8000:8000'
      - '9000:9000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock    
  web:
    image: microweber/php74-apache
    ports:
      - '80:80'
    restart: always
    links:
      - db
    depends_on:
      - db
    volumes: 
      - ./code:/var/www/html
  db:
    image: mysql:8.0
    restart: always
    ports:
     - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456aA@
      MYSQL_DATABASE: shop_yii
      MYSQL_USER: user_shop
      MYSQL_PASSWORD: 123456aA@
  myadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '81:80'
    environment:
      PMA_HOST: db
